# AUTOGENERATED 2022-11-13T13:27:34Z
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

# volume_id: vol-00f98604d4db256ee
# volume_id: vol-021a8417733be96c0

resource "aws_ec2_tag" "snapshot_snap-0e75ec66522362283" {
  for_each = {
    "Cluster" : "qa-box"
    "Env" : "qa"
    "Name" : "test-01"
    "Service" : "qa-box"
  }
  resource_id = "snap-0e75ec66522362283"
  key         = each.key
  value       = each.value
}
# volume_id: vol-0a5bda9a14a06e195

resource "aws_ec2_tag" "snapshot_snap-0bfe544df74a10627" {
  for_each = {
    "Cluster" : "api"
    "Env" : "canary"
    "Name" : "test-02"
    "Service" : "api"
  }
  resource_id = "snap-0bfe544df74a10627"
  key         = each.key
  value       = each.value
}
# volume_id: vol-0e41d98ea1edb9f2b
