# AUTOGENERATED 2022-11-15T02:23:31Z
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

# Instance Name: test01
resource "aws_ec2_tag" "volume_vol-0daf30c67fa713965" {
    for_each = {
                "Env" : "qa"
                "Name" : "test01"
                "Service" : "qa"
            }
    resource_id = "vol-0daf30c67fa713965"
    key = each.key
    value = each.value
}
# Instance Name: crdb-01
resource "aws_ec2_tag" "volume_vol-026589fb4b682dc85" {
    for_each = {
                "Env" : "canary"
                "Name" : "crdb-01"
                "Service" : "cr-db"
            }
    resource_id = "vol-026589fb4b682dc85"
    key = each.key
    value = each.value
}
# Instance Name: api-01
resource "aws_ec2_tag" "volume_vol-0232eaaa7f4f783eb" {
    for_each = {
                "Env" : "canary"
                "Name" : "api-01"
                "Service" : "api"
            }
    resource_id = "vol-0232eaaa7f4f783eb"
    key = each.key
    value = each.value
}
