# AUTOGENERATED 2022-11-07T01:25:57Z
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

# Instance Name: test01
resource "aws_ec2_tag" "volume_vol-08d0806eb02194f59" {
    for_each = {
                "Name" : "test01"
                "Service" : "qa-box"
            }
    resource_id = "vol-08d0806eb02194f59"
    key = each.key
    value = each.value
}
