# AUTOGENERATED 2022-10-11T03:23:23Z
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

resource "aws_ec2_tag" "ec2_i-09dedae90fdb30f20" {
  for_each = { 
    "Name" : "test-3", 
    "Team" : "devOps", 
    "Service" : "rpc",
  }
  resource_id = "i-09dedae90fdb30f20"
  key         = each.key
  value       = each.value
}

