# AUTOGENERATED 2022-11-07T01:25:57Z
terraform import 'aws_ec2_tag.ec2_i-04bcc7a0f1feb8a0e["Name"]' i-04bcc7a0f1feb8a0e,"Name"
terraform import 'aws_ec2_tag.ec2_i-04bcc7a0f1feb8a0e["Service"]' i-04bcc7a0f1feb8a0e,"Service"
