# AUTOGENERATED 2022-11-15T02:23:31Z
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

# Name: test01
resource "aws_ec2_tag" "ec2_i-04733f95a3b2a72a7" {
  for_each = {
        "Env" : "qa"
        "Name" : "test01"
        "Service" : "qa"
      }
  resource_id = "i-04733f95a3b2a72a7"
  key         = each.key
  value       = each.value
}

# Name: crdb-01
resource "aws_ec2_tag" "ec2_i-0aba5dbb6690fade7" {
  for_each = {
        "Env" : "canary"
        "Name" : "crdb-01"
        "Service" : "cr-db"
      }
  resource_id = "i-0aba5dbb6690fade7"
  key         = each.key
  value       = each.value
}

# Name: api-01
resource "aws_ec2_tag" "ec2_i-062e6e356b8b982c9" {
  for_each = {
        "Env" : "canary"
        "Name" : "api-01"
        "Service" : "api"
      }
  resource_id = "i-062e6e356b8b982c9"
  key         = each.key
  value       = each.value
}

