# AUTOGENERATED 2022-11-07T01:25:57Z
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

# Name: test01
resource "aws_ec2_tag" "ec2_i-04bcc7a0f1feb8a0e" {
  for_each = {
        "Name" : "test01"
        "Service" : "qa-box"
      }
  resource_id = "i-04bcc7a0f1feb8a0e"
  key         = each.key
  value       = each.value
}

